theme = "dracula_at_night"

[editor]
line-number = "absolute"
mouse = true
rulers = []
bufferline = "multiple"
color-modes = true

[editor.lsp]
display-inlay-hints = true
snippets = true

[editor.cursor-shape]
insert = "bar"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-r = ":reload-all"
