#!/bin/sh

export PATH="$PATH:$HOME/.local/bin/"

[ -f ~/.fehbg ] && ~/.fehbg &
xrdb -merge ~/.Xresources &
setxkbmap -option caps:esc us &

status_bar &
setup_xinput &
setup_systray &

exec dwm > ~/.local/share/dwm/dwm.log 2>&1
