#!/bin/bash

# Load colors from Xresources.
declare -A colors=()
while read -r k v; do
    colors["$k"]="$v"
done < <(xrdb -query | grep dmenu | sed 's/dmenu\.\(\w\+\):\s\+\(#[0-9a-f]\)\+/\1 \2/')

ans=$(echo -e 'No\nYes' | \
        dmenu -p "Are you sure you want to quit?" \
    )
[ "$ans" = "Yes" ] && xsetroot -name "fsignal:9"
