#!/bin/sh

# Kill already running processes of this file.
ps -aux \
    | grep .local/bin/status_bar \
    | awk '{print $2}' \
    | grep -v $$ \
    | xargs kill -9


# $1 is the filter to use
filter_and_get_names_nmcli() {
    output="$( \
        nmcli -t connection show --active \
        | grep $1 \
        | awk -F ':' '{ print $1 }' \
    )"
    [ "$output" ] && echo $output
}

get_eth_info() {
    [ "$(filter_and_get_names_nmcli ethernet)" ] && echo "[eth: connected]"
}

get_wifi_info() {
    [ "$(nmcli radio wifi)" = "disabled" ] && return

    ssid="$(filter_and_get_names_nmcli wireless)"
    
    [ "$ssid" ] && echo "[wifi: $ssid]" || echo "[wifi: enabled]"
}

get_vpn_info() {
    vpn_name="$(filter_and_get_names_nmcli vpn)" 
    [ $vpn_name ] && echo "[vpn: $vpn_name]"
}

while true; do

    internet="$(get_vpn_info) $(get_eth_info) $(get_wifi_info)"

    battery="$(cat /sys/class/power_supply/BAT0/capacity)% $(cat /sys/class/power_supply/BAT0/status)"

    layout="$(setxkbmap -query | grep layout)"

    date="$(date)"

    status_bar="$internet | $battery | $layout | $date"
    bar="$(echo $status_bar | sed 's/\+/ /g')"  # trim excessive whitespace
    xsetroot -name " $bar "
    sleep 1
done
